version: '3.3'

services:
  nuxt:
    build:
      context: .
    image: nuxt_dev
    container_name: nuxt_dev
    command: npm run dev
    env_file:
      - .env.development.local
    volumes:
    - .:/app
    - /app/node_modules
    ports:
      - "3000:3000"